package modelo;
// Generated 18 ene 2022 16:14:49 by Hibernate Tools 5.5.7.Final

/**
 * DatosHorario generated by hbm2java
 */
public class DatosHorario implements java.io.Serializable {

	private DatosHorarioId id;
	private Estaciones estaciones;
	private String comgm3;
	private String co8hmgm3;
	private String nogm3;
	private String no2;
	private String no2ica;
	private String noxgm3;
	private String pm10;
	private String pm10ica;
	private String pm25;
	private String pm25ica;
	private String so2;
	private String so2ica;
	private String icaestacion;

	public DatosHorario() {
	}

	public DatosHorario(DatosHorarioId id, Estaciones estaciones, String comgm3, String co8hmgm3, String nogm3,
			String no2, String no2ica, String noxgm3, String pm10, String pm10ica, String pm25, String pm25ica,
			String so2, String so2ica, String icaestacion) {
		this.id = id;
		this.estaciones = estaciones;
		this.comgm3 = comgm3;
		this.co8hmgm3 = co8hmgm3;
		this.nogm3 = nogm3;
		this.no2 = no2;
		this.no2ica = no2ica;
		this.noxgm3 = noxgm3;
		this.pm10 = pm10;
		this.pm10ica = pm10ica;
		this.pm25 = pm25;
		this.pm25ica = pm25ica;
		this.so2 = so2;
		this.so2ica = so2ica;
		this.icaestacion = icaestacion;
	}

	public DatosHorarioId getId() {
		return this.id;
	}

	public void setId(DatosHorarioId id) {
		this.id = id;
	}

	public Estaciones getEstaciones() {
		return this.estaciones;
	}

	public void setEstaciones(Estaciones estaciones) {
		this.estaciones = estaciones;
	}

	public String getComgm3() {
		return this.comgm3;
	}

	public void setComgm3(String comgm3) {
		this.comgm3 = comgm3;
	}

	public String getCo8hmgm3() {
		return this.co8hmgm3;
	}

	public void setCo8hmgm3(String co8hmgm3) {
		this.co8hmgm3 = co8hmgm3;
	}

	public String getNogm3() {
		return this.nogm3;
	}

	public void setNogm3(String nogm3) {
		this.nogm3 = nogm3;
	}

	public String getNo2() {
		return this.no2;
	}

	public void setNo2(String no2) {
		this.no2 = no2;
	}

	public String getNo2ica() {
		return this.no2ica;
	}

	public void setNo2ica(String no2ica) {
		this.no2ica = no2ica;
	}

	public String getNoxgm3() {
		return this.noxgm3;
	}

	public void setNoxgm3(String noxgm3) {
		this.noxgm3 = noxgm3;
	}

	public String getPm10() {
		return this.pm10;
	}

	public void setPm10(String pm10) {
		this.pm10 = pm10;
	}

	public String getPm10ica() {
		return this.pm10ica;
	}

	public void setPm10ica(String pm10ica) {
		this.pm10ica = pm10ica;
	}

	public String getPm25() {
		return this.pm25;
	}

	public void setPm25(String pm25) {
		this.pm25 = pm25;
	}

	public String getPm25ica() {
		return this.pm25ica;
	}

	public void setPm25ica(String pm25ica) {
		this.pm25ica = pm25ica;
	}

	public String getSo2() {
		return this.so2;
	}

	public void setSo2(String so2) {
		this.so2 = so2;
	}

	public String getSo2ica() {
		return this.so2ica;
	}

	public void setSo2ica(String so2ica) {
		this.so2ica = so2ica;
	}

	public String getIcaestacion() {
		return this.icaestacion;
	}

	public void setIcaestacion(String icaestacion) {
		this.icaestacion = icaestacion;
	}

}
