package modelo;
// Generated 18 ene 2022 17:47:49 by Hibernate Tools 5.5.7.Final

import java.util.Date;

/**
 * DatosDiarioId generated by hbm2java
 */
public class DatosDiarioId implements java.io.Serializable {

	private int codEstacion;
	private Date fecha;

	public DatosDiarioId() {
	}

	public DatosDiarioId(int codEstacion, Date fecha) {
		this.codEstacion = codEstacion;
		this.fecha = fecha;
	}

	public int getCodEstacion() {
		return this.codEstacion;
	}

	public void setCodEstacion(int codEstacion) {
		this.codEstacion = codEstacion;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DatosDiarioId))
			return false;
		DatosDiarioId castOther = (DatosDiarioId) other;

		return (this.getCodEstacion() == castOther.getCodEstacion())
				&& ((this.getFecha() == castOther.getFecha()) || (this.getFecha() != null
						&& castOther.getFecha() != null && this.getFecha().equals(castOther.getFecha())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodEstacion();
		result = 37 * result + (getFecha() == null ? 0 : this.getFecha().hashCode());
		return result;
	}

}
