package modelo;
// Generated 23 ene 2022 19:06:22 by Hibernate Tools 5.5.7.Final

/**
 * DatosDiario generated by hbm2java
 */
public class DatosDiario implements java.io.Serializable {

	private DatosDiarioId id;
	private Estaciones estaciones;
	private String comgm3;
	private String co8hmgm3;
	private String nogm3;
	private String no2gm3;
	private String noxgm3;
	private String pm10gm3;
	private String pm25gm3;
	private String so2gm3;

	public DatosDiario() {
	}

	public DatosDiario(DatosDiarioId id, Estaciones estaciones) {
		this.id = id;
		this.estaciones = estaciones;
	}

	public DatosDiario(DatosDiarioId id, Estaciones estaciones, String comgm3, String co8hmgm3, String nogm3,
			String no2gm3, String noxgm3, String pm10gm3, String pm25gm3, String so2gm3) {
		this.id = id;
		this.estaciones = estaciones;
		this.comgm3 = comgm3;
		this.co8hmgm3 = co8hmgm3;
		this.nogm3 = nogm3;
		this.no2gm3 = no2gm3;
		this.noxgm3 = noxgm3;
		this.pm10gm3 = pm10gm3;
		this.pm25gm3 = pm25gm3;
		this.so2gm3 = so2gm3;
	}

	public DatosDiarioId getId() {
		return this.id;
	}

	public void setId(DatosDiarioId id) {
		this.id = id;
	}

	public Estaciones getEstaciones() {
		return this.estaciones;
	}

	public void setEstaciones(Estaciones estaciones) {
		this.estaciones = estaciones;
	}

	public String getComgm3() {
		return this.comgm3;
	}

	public void setComgm3(String comgm3) {
		this.comgm3 = comgm3;
	}

	public String getCo8hmgm3() {
		return this.co8hmgm3;
	}

	public void setCo8hmgm3(String co8hmgm3) {
		this.co8hmgm3 = co8hmgm3;
	}

	public String getNogm3() {
		return this.nogm3;
	}

	public void setNogm3(String nogm3) {
		this.nogm3 = nogm3;
	}

	public String getNo2gm3() {
		return this.no2gm3;
	}

	public void setNo2gm3(String no2gm3) {
		this.no2gm3 = no2gm3;
	}

	public String getNoxgm3() {
		return this.noxgm3;
	}

	public void setNoxgm3(String noxgm3) {
		this.noxgm3 = noxgm3;
	}

	public String getPm10gm3() {
		return this.pm10gm3;
	}

	public void setPm10gm3(String pm10gm3) {
		this.pm10gm3 = pm10gm3;
	}

	public String getPm25gm3() {
		return this.pm25gm3;
	}

	public void setPm25gm3(String pm25gm3) {
		this.pm25gm3 = pm25gm3;
	}

	public String getSo2gm3() {
		return this.so2gm3;
	}

	public void setSo2gm3(String so2gm3) {
		this.so2gm3 = so2gm3;
	}

}
