package modelo;
// Generated 18 ene 2022 16:14:49 by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Estaciones generated by hbm2java
 */
public class Estaciones implements java.io.Serializable {

	private int codEstacion;
	private Municipios municipios;
	private String nombre;
	private double coordenadaX;
	private double coordenadaY;
	private Set datosDiarios = new HashSet(0);
	private Set datosHorarios = new HashSet(0);

	public Estaciones() {
	}

	public Estaciones(int codEstacion, Municipios municipios, String nombre, double coordenadaX, double coordenadaY) {
		this.codEstacion = codEstacion;
		this.municipios = municipios;
		this.nombre = nombre;
		this.coordenadaX = coordenadaX;
		this.coordenadaY = coordenadaY;
	}

	public Estaciones(int codEstacion, Municipios municipios, String nombre, double coordenadaX, double coordenadaY,
			Set datosDiarios, Set datosHorarios) {
		this.codEstacion = codEstacion;
		this.municipios = municipios;
		this.nombre = nombre;
		this.coordenadaX = coordenadaX;
		this.coordenadaY = coordenadaY;
		this.datosDiarios = datosDiarios;
		this.datosHorarios = datosHorarios;
	}

	public int getCodEstacion() {
		return this.codEstacion;
	}

	public void setCodEstacion(int codEstacion) {
		this.codEstacion = codEstacion;
	}

	public Municipios getMunicipios() {
		return this.municipios;
	}

	public void setMunicipios(Municipios municipios) {
		this.municipios = municipios;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public double getCoordenadaX() {
		return this.coordenadaX;
	}

	public void setCoordenadaX(double coordenadaX) {
		this.coordenadaX = coordenadaX;
	}

	public double getCoordenadaY() {
		return this.coordenadaY;
	}

	public void setCoordenadaY(double coordenadaY) {
		this.coordenadaY = coordenadaY;
	}

	public Set getDatosDiarios() {
		return this.datosDiarios;
	}

	public void setDatosDiarios(Set datosDiarios) {
		this.datosDiarios = datosDiarios;
	}

	public Set getDatosHorarios() {
		return this.datosHorarios;
	}

	public void setDatosHorarios(Set datosHorarios) {
		this.datosHorarios = datosHorarios;
	}

}
