package modelo;
// Generated 18 ene 2022 16:14:49 by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Municipios generated by hbm2java
 */
public class Municipios implements java.io.Serializable {

	private int codMunicipio;
	private Provincias provincias;
	private String nombre;
	private String descripcion;
	private Set espaciosNaturaleses = new HashSet(0);
	private Set espaciosNaturaleses_1 = new HashSet(0);
	private Set estacioneses = new HashSet(0);
	private Set usuarioses = new HashSet(0);

	public Municipios() {
	}

	public Municipios(int codMunicipio, Provincias provincias, String nombre, String descripcion) {
		this.codMunicipio = codMunicipio;
		this.provincias = provincias;
		this.nombre = nombre;
		this.descripcion = descripcion;
	}

	public Municipios(int codMunicipio, Provincias provincias, String nombre, String descripcion,
			Set espaciosNaturaleses, Set espaciosNaturaleses_1, Set estacioneses, Set usuarioses) {
		this.codMunicipio = codMunicipio;
		this.provincias = provincias;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.espaciosNaturaleses = espaciosNaturaleses;
		this.espaciosNaturaleses_1 = espaciosNaturaleses_1;
		this.estacioneses = estacioneses;
		this.usuarioses = usuarioses;
	}

	public int getCodMunicipio() {
		return this.codMunicipio;
	}

	public void setCodMunicipio(int codMunicipio) {
		this.codMunicipio = codMunicipio;
	}

	public Provincias getProvincias() {
		return this.provincias;
	}

	public void setProvincias(Provincias provincias) {
		this.provincias = provincias;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getEspaciosNaturaleses() {
		return this.espaciosNaturaleses;
	}

	public void setEspaciosNaturaleses(Set espaciosNaturaleses) {
		this.espaciosNaturaleses = espaciosNaturaleses;
	}

	public Set getEspaciosNaturaleses_1() {
		return this.espaciosNaturaleses_1;
	}

	public void setEspaciosNaturaleses_1(Set espaciosNaturaleses_1) {
		this.espaciosNaturaleses_1 = espaciosNaturaleses_1;
	}

	public Set getEstacioneses() {
		return this.estacioneses;
	}

	public void setEstacioneses(Set estacioneses) {
		this.estacioneses = estacioneses;
	}

	public Set getUsuarioses() {
		return this.usuarioses;
	}

	public void setUsuarioses(Set usuarioses) {
		this.usuarioses = usuarioses;
	}

}
