package modelo;
// Generated 18 ene 2022 16:14:49 by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Provincias generated by hbm2java
 */
public class Provincias implements java.io.Serializable {

	private int codProvincia;
	private String nomProvincia;
	private Set municipioses = new HashSet(0);

	public Provincias() {
	}

	public Provincias(int codProvincia, String nomProvincia) {
		this.codProvincia = codProvincia;
		this.nomProvincia = nomProvincia;
	}

	public Provincias(int codProvincia, String nomProvincia, Set municipioses) {
		this.codProvincia = codProvincia;
		this.nomProvincia = nomProvincia;
		this.municipioses = municipioses;
	}

	public int getCodProvincia() {
		return this.codProvincia;
	}

	public void setCodProvincia(int codProvincia) {
		this.codProvincia = codProvincia;
	}

	public String getNomProvincia() {
		return this.nomProvincia;
	}

	public void setNomProvincia(String nomProvincia) {
		this.nomProvincia = nomProvincia;
	}

	public Set getMunicipioses() {
		return this.municipioses;
	}

	public void setMunicipioses(Set municipioses) {
		this.municipioses = municipioses;
	}

}
