package modelo;
// Generated 23 ene 2022 19:06:22 by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

	private int codUsuario;
	private String nombre;
	private String contrasenia;
	private Set municipioses = new HashSet(0);
	private Set espaciosNaturaleses = new HashSet(0);

	public Usuarios() {
	}

	public Usuarios(int codUsuario, String nombre, String contrasenia) {
		this.codUsuario = codUsuario;
		this.nombre = nombre;
		this.contrasenia = contrasenia;
	}

	public Usuarios(int codUsuario, String nombre, String contrasenia, Set municipioses, Set espaciosNaturaleses) {
		this.codUsuario = codUsuario;
		this.nombre = nombre;
		this.contrasenia = contrasenia;
		this.municipioses = municipioses;
		this.espaciosNaturaleses = espaciosNaturaleses;
	}

	public int getCodUsuario() {
		return this.codUsuario;
	}

	public void setCodUsuario(int codUsuario) {
		this.codUsuario = codUsuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getContrasenia() {
		return this.contrasenia;
	}

	public void setContrasenia(String contrasenia) {
		this.contrasenia = contrasenia;
	}

	public Set getMunicipioses() {
		return this.municipioses;
	}

	public void setMunicipioses(Set municipioses) {
		this.municipioses = municipioses;
	}

	public Set getEspaciosNaturaleses() {
		return this.espaciosNaturaleses;
	}

	public void setEspaciosNaturaleses(Set espaciosNaturaleses) {
		this.espaciosNaturaleses = espaciosNaturaleses;
	}

}
