package modelo;
// Generated 16 dic 2021 18:35:54 by Hibernate Tools 5.5.7.Final

/**
 * Datos generated by hbm2java
 */
public class Datos implements java.io.Serializable {

	private DatosId id;
	private Estaciones estaciones;
	private String precipitaciones;

	private int temperatura;

	private int velocidadViento;

	public Datos() {
	}

	public Datos(DatosId id, Estaciones estaciones, String precipitaciones, int temperatura, int velocidadViento) {
		this.id = id;
		this.estaciones = estaciones;
		this.precipitaciones = precipitaciones;
		this.temperatura = temperatura;
		this.velocidadViento = velocidadViento;
	}

	public DatosId getId() {
		return this.id;
	}

	public void setId(DatosId id) {
		this.id = id;
	}

	public Estaciones getEstaciones() {
		return this.estaciones;
	}

	public void setEstaciones(Estaciones estaciones) {
		this.estaciones = estaciones;
	}

	public String getPrecipitaciones() {
		return this.precipitaciones;
	}

	public void setPrecipitaciones(String precipitaciones) {
		this.precipitaciones = precipitaciones;
	}

	public int getTemperatura() {
		return this.temperatura;
	}

	public void setTemperatura(int temperatura) {
		this.temperatura = temperatura;
	}

	public int getVelocidadViento() {
		return this.velocidadViento;
	}

	public void setVelocidadViento(int velocidadViento) {
		this.velocidadViento = velocidadViento;
	}

}
